/// Flutter icons MyFlutterApp
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
///
///
import 'package:flutter/widgets.dart';

class MoreFlutterIcons {
  MoreFlutterIcons._();

  static const _kFontFam = 'MoreFlutterIcons';

  static const IconData voucher__1_ = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData deals = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData priceTracker = IconData(0xe804, fontFamily: _kFontFam);
  static const IconData profile = IconData(0xe805, fontFamily: _kFontFam);
  static const IconData foursquare = IconData(0xe806, fontFamily: _kFontFam);
  static const IconData brochure = IconData(0xe807, fontFamily: _kFontFam);
  static const IconData purchaseHistory =
      IconData(0xe808, fontFamily: _kFontFam);
  static const IconData inbox = IconData(0xe809, fontFamily: _kFontFam);
  static const IconData retailers = IconData(0xe80a, fontFamily: _kFontFam);
}
